<form action="<?= $this->getUrl('crud/post/save') ?>" method="POST">
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Name</label>
        <input type="text" name="name" class="form-control" aria-describedby="emailHelp">
    </div>
    </br>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Content</label>
        <input type="text" name="content" class="form-control" aria-describedby="emailHelp">
    </div>
  </br>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>